/**
 * 
 * @type Array
 * @constant
 */
imageEditor.CLIPART_CATEGORIES = [
    'all', 'banners', 'ribbons', 'words', 'washi tapes', 'frames'
];

/**
 * 
 * @type Array
 * @constant
 */
imageEditor.SHAPES = [{
        id: 1,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/banner.png"
    }, {
        id: 2,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/blueribbon.png"
    }, {
        id: 3,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/graylace2.png"
    }, {
        id: 4,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/graywashitape.png"
    }, {
        id: 5,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/lace.png"
    }, {
        id: 6,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/photoedge.png"
    }, {
        id: 7,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/poppy.png"
    }, {
        id: 8,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/purplewatercolor.png"
    }, {
        id: 9,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/ribbonwatercolor.png"
    }, {
        id: 10,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/washitape.png"
    }, {
        id: 11,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/watercolorfeathers.png"
    }, {
        id: 12,
        type: "clipart",
        tags: "banners",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/watercolorlace.png"
    }, {
        id: 13,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 600,
        scale: 0.5,
        src: "clipart/whiteribbon.png"
    }, {
        id: 14,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 275,
        scale: 0.5,
        src: "clipart/grayribbon.png"
    }, {
        id: 15,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/line.png"
    }, {
        id: 16,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/ornament.png"
    }, {
        id: 17,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/swirl.png"
    }, {
        id: 18,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 246,
        scale: 0.5,
        src: "clipart/textured.png"
    }, {
        id: 19,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/textured2.png"
    }, {
        id: 20,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/white.png"
    }, {
        id: 21,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 209,
        scale: 0.5,
        src: "clipart/Untitled1-3.png"
    }, {
        id: 22,
        type: "clipart",
        tags: "ribbons",
        width: 600,
        height: 177,
        scale: 0.5,
        src: "clipart/Untitled-3.png"
    }, {
        id: 23,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/aboutme.png"
    }, {
        id: 24,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/blackhello.png"
    }, {
        id: 25,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/grayaboutme.png"
    }, {
        id: 26,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/graywelcome.png"
    }, {
        id: 27,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/hellograycallig.png"
    }, {
        id: 28,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 184,
        scale: 0.5,
        src: "clipart/welcomeblack.png"
    }, {
        id: 29,
        type: "clipart",
        tags: "words",
        width: 600,
        height: 205,
        scale: 0.5,
        src: "clipart/whitewelcome.png"
    }, {
        id: 30,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 156,
        scale: 0.5,
        src: "clipart/graybottompaint.png"
    }, {
        id: 31,
        type: "clipart",
        tags: "washi tapes",
        width: 446,
        height: 103,
        scale: 0.5,
        src: "clipart/brown.png"
    }, {
        id: 32,
        type: "clipart",
        tags: "washi tapes",
        width: 445,
        height: 104,
        scale: 0.5,
        src: "clipart/coralbluescrapbookpaper.png"
    }, {
        id: 33,
        type: "clipart",
        tags: "washi tapes",
        width: 448,
        height: 105,
        scale: 0.5,
        src: "clipart/dots.png"
    }, {
        id: 34,
        type: "clipart",
        tags: "washi tapes",
        width: 446,
        height: 103,
        scale: 0.5,
        src: "clipart/graystripes.png"
    }, {
        id: 35,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 138,
        scale: 0.5,
        src: "clipart/paint.png"
    }, {
        id: 36,
        type: "clipart",
        tags: "washi tapes",
        width: 446,
        height: 103,
        scale: 0.5,
        src: "clipart/plainwhite.png"
    }, {
        id: 37,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-1.png"
    }, {
        id: 38,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-2.png"
    }, {
        id: 39,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-3-.png"
    }, {
        id: 40,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-4.png"
    }, {
        id: 41,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 133,
        scale: 0.5,
        src: "clipart/Untitled-5.png"
    }, {
        id: 42,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 133,
        scale: 0.5,
        src: "clipart/Untitled-6.png"
    }, {
        id: 43,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 133,
        scale: 0.5,
        src: "clipart/Untitled-7.png"
    }, {
        id: 44,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-8.png"
    }, {
        id: 45,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 162,
        scale: 0.5,
        src: "clipart/Untitled-9.png"
    }, {
        id: 46,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-10.png"
    }, {
        id: 47,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-11.png"
    }, {
        id: 48,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-12.png"
    }, {
        id: 49,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-13.png"
    }, {
        id: 50,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-14.png"
    }, {
        id: 51,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-15.png"
    }, {
        id: 52,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-16.png"
    }, {
        id: 53,
        type: "clipart",
        tags: "washi tapes",
        width: 600,
        height: 150,
        scale: 0.5,
        src: "clipart/Untitled-17.png"
    }, {
        id: 54,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-basicsquare.png"
    }, {
        id: 55,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-black.png"
    }, {
        id: 56,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-blackcircle.png"
    }, {
        id: 57,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 517,
        scale: 1,
        src: "frame/frame-blacklineframe.png"
    }, {
        id: 58,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-blacksquare.png"
    }, {
        id: 59,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-circle.png"
    }, {
        id:60,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-circleblack.png"
    }, {
        id: 61,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-cutcornerframe.png"
    }, {
        id: 62,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 295,
        scale: 1,
        src: "frame/frame-frame1.png"
    }, {
        id: 63,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 498,
        scale: 1,
        src: "frame/frame-geoframe.png"
    }, {
        id: 64,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 498,
        scale: 1,
        src: "frame/frame-geoframewhite.png"
    }, {
        id: 65,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-grayframe.png"
    }, {
        id: 66,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-grayoval.png"
    }, {
        id: 67,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 517,
        scale: 1,
        src: "frame/frame-lightwhitegrunge.png"
    }, {
        id: 68,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-oval.png"
    }, {
        id: 69,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-ovalwithgray.png"
    }, {
        id: 70,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-polaroidframe.png"
    }, {
        id: 71,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 517,
        scale: 1,
        src: "frame/frame-redlinegrunge.png"
    }, {
        id: 72,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-roundedrect.png"
    }, {
        id: 73,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-roundedrectlightgray.png"
    }, {
        id: 74,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-roundedrectwithgray.png"
    }, {
        id: 75,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-subtlegrungeframe.png"
    }, {
        id: 76,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-subtlewhiteframe.png"
    }, {
        id: 77,
        type: "clipart",
        tags: "frames",
        width: 600,
        height: 600,
        scale: 1,
        src: "frame/frame-tanframe.png"
    }];